version: 2
updates:
  - package-ecosystem: gomod
    directory: /backend
    schedule:
      interval: weekly
    open-pull-requests-limit: 5
    groups:
      go-runtime-dependencies:
        dependency-type: production
      go-development-dependencies:
        dependency-type: development

  - package-ecosystem: npm
    directory: /frontend
    schedule:
      interval: weekly
    open-pull-requests-limit: 5
    groups:
      frontend-production-dependencies:
        dependency-type: production
      frontend-development-dependencies:
        dependency-type: development

  - package-ecosystem: npm
    directory: /
    schedule:
      interval: weekly
    open-pull-requests-limit: 3
    groups:
      browser-test-dependencies:
        patterns:
          - '*'

  - package-ecosystem: github-actions
    directory: /
    schedule:
      interval: weekly
    open-pull-requests-limit: 5
    groups:
      github-actions:
        patterns:
          - '*'

  - package-ecosystem: docker
    directory: /deploy/docker
    schedule:
      interval: weekly
    open-pull-requests-limit: 3
