import { ContractTimelineDocument, ContractTimelineClip } from '../contract/timeline';
import { VideoTimelineDocument, VideoTimelineClip } from '../../../frontend/src/types/video';

export function adaptTimelineV1ToV2(v1: VideoTimelineDocument): ContractTimelineDocument {
  return {
    version: 2,
    width: v1.width,
    height: v1.height,
    fps: v1.fps,
    durationMs: v1.duration_ms,
    aspectRatio: v1.aspect_ratio || '16:9',
    backgroundColor: v1.background_color || '#000000',
    colorSpace: 'srgb',
    scenes: (v1.scenes || []).map((scene) => ({
      id: scene.id,
      name: scene.name,
      startMs: scene.start_ms,
      durationMs: scene.duration_ms,
      color: scene.color,
      camera: scene.camera ? {
        x: scene.camera.x,
        y: scene.camera.y,
        z: scene.camera.z,
        rotationX: scene.camera.rotation_x,
        rotationY: scene.camera.rotation_y,
        rotationZ: scene.camera.rotation_z,
        fieldOfView: scene.camera.field_of_view,
        focusDepth: scene.camera.focus_depth,
      } : undefined,
      effects: (scene.effects || []).map((e) => ({
        id: e.id,
        type: e.type,
        amount: e.amount,
        enabled: e.enabled,
        params: e.params,
      })),
    })),
    tracks: v1.tracks.map((track, trackIdx) => ({
      id: track.id,
      name: track.name,
      type: track.type || 'video',
      index: track.index ?? trackIdx,
      muted: track.muted,
      solo: track.solo,
      locked: track.locked,
      visible: track.visible,
      volume: track.volume,
      pan: track.pan,
      clips: track.clips.map((clip) => adaptClipV1ToV2(clip)),
    })),
    captions: (v1.captions || []).map((cap) => ({
      id: cap.id,
      startMs: cap.start_ms,
      endMs: cap.end_ms,
      text: cap.text,
    })),
    metadata: v1.metadata,
  };
}

export function adaptClipV1ToV2(clip: VideoTimelineClip): ContractTimelineClip {
  return {
    id: clip.id,
    assetId: clip.asset_id,
    startMs: clip.start_ms,
    durationMs: clip.duration_ms,
    trimInMs: clip.trim_in_ms,
    trimOutMs: clip.trim_out_ms,
    playbackRate: clip.playback_rate,
    volume: clip.volume,
    pan: clip.pan,
    fadeInMs: clip.fade_in_ms,
    fadeOutMs: clip.fade_out_ms,
    muted: clip.muted,
    audioOnly: clip.audio_only,
    zIndex: clip.z_index,
    fitMode: (clip.fit_mode as any) || 'contain',
    transform: clip.transform ? {
      x: clip.transform.x,
      y: clip.transform.y,
      z: clip.transform.z,
      scaleX: clip.transform.scale_x,
      scaleY: clip.transform.scale_y,
      scaleZ: clip.transform.scale_z,
      rotationX: clip.transform.rotation_x,
      rotationY: clip.transform.rotation_y,
      rotationZ: clip.transform.rotation_z,
      anchorX: clip.transform.anchor_x,
      anchorY: clip.transform.anchor_y,
      opacity: clip.transform.opacity,
    } : undefined,
    crop: clip.crop ? {
      top: clip.crop.top,
      right: clip.crop.right,
      bottom: clip.crop.bottom,
      left: clip.crop.left,
      feather: clip.crop.feather,
      shape: clip.crop.shape as any,
      cornerRadius: clip.crop.corner_radius,
    } : undefined,
    text: clip.text ? {
      text: clip.text.text,
      fontFamily: clip.text.font_family,
      fontSize: clip.text.font_size,
      fontWeight: clip.text.font_weight,
      fontStyle: clip.text.font_style,
      color: clip.text.color,
      background: clip.text.background,
      stroke: clip.text.stroke,
      strokeWidth: clip.text.stroke_width,
      shadow: clip.text.shadow,
      textAlign: clip.text.text_align as any,
      lineHeight: clip.text.line_height,
      letterSpacing: clip.text.letter_spacing,
      borderRadius: clip.text.border_radius,
      padding: clip.text.padding,
      wrapWidth: clip.text.wrap_width,
    } : undefined,
    shape: clip.shape ? {
      kind: clip.shape.kind,
      fill: clip.shape.fill,
      stroke: clip.shape.stroke,
      strokeWidth: clip.shape.stroke_width,
      cornerRadius: clip.shape.corner_radius,
      opacity: clip.shape.opacity,
      blurRadius: clip.shape.blur_radius,
    } : undefined,
    cursor: clip.cursor ? {
      glyph: clip.cursor.glyph,
      size: clip.cursor.size,
      color: clip.cursor.color,
      highlight: clip.cursor.highlight,
      smoothing: clip.cursor.smoothing,
      points: (clip.cursor.points || []).map((pt) => ({
        timeMs: pt.time_ms,
        x: pt.x,
        y: pt.y,
        click: pt.click,
      })),
    } : undefined,
    effects: (clip.effects || []).map((e) => ({
      id: e.id,
      type: e.type,
      amount: e.amount,
      enabled: e.enabled,
      params: e.params,
    })),
    transitions: (clip.transitions || []).map((t) => ({
      id: t.id,
      type: t.type,
      durationMs: t.duration_ms,
      edge: t.edge as any,
      direction: t.direction,
      params: t.params,
    })),
    keyframes: (clip.keyframes || []).map((k) => ({
      id: k.id,
      property: k.property,
      timeMs: k.time_ms,
      value: k.value,
      easing: k.easing as any,
    })),
  };
}
