from pathlib import Path

PR = "294"
PARENT = "9850370c2aa25a076f3272077062aeab08c1f326"


def replace_once(path: str, old: str, new: str) -> None:
    p = Path(path)
    text = p.read_text(encoding="utf-8")
    count = text.count(old)
    if count != 1:
        raise SystemExit(f"{path}: expected one match, found {count}: {old[:140]!r}")
    p.write_text(text.replace(old, new, 1), encoding="utf-8")


# Wire the project background into the pixelate Canvas consumer and make the
# execution key sensitive to it so a background edit cannot reuse stale pixels.
consumer = "frontend/src/components/video/PreviewPixelateBackdropConsumer.tsx"
replace_once(
    consumer,
    """ * Structural admission and runtime decoded-pixel proof both fail closed: normal\n * playback, poster-budget sources, transparent target regions, and unsupported\n * canonical state leave the established CSS approximation untouched.\n""",
    """ * Structural admission and runtime decoded-pixel proof both fail closed: normal\n * playback, poster-budget sources, unsupported canonical state, and decoded\n * video that cannot prove its source frame opaque leave the established CSS\n * approximation untouched. Transparent/partial-alpha images are admitted only\n * after canonical project-background composition in PreviewPixelateCanvas.\n""",
)
replace_once(
    consumer,
    """  const canvasHeight = timeline?.canvas.height || 1080;\n  const stageScale = stageSize.width > 0 ? stageSize.width / canvasWidth : 0;\n""",
    """  const canvasHeight = timeline?.canvas.height || 1080;\n  const canvasBackground = timeline?.canvas.background || '#000000';\n  const stageScale = stageSize.width > 0 ? stageSize.width / canvasWidth : 0;\n""",
)
replace_once(
    consumer,
    """    ? `${deterministicFrame}:${plan.target.clip.id}:${plan.backdrop.clip.id}:${canvasWidth}x${canvasHeight}`\n""",
    """    ? `${deterministicFrame}:${plan.target.clip.id}:${plan.backdrop.clip.id}:${canvasWidth}x${canvasHeight}:${canvasBackground}`\n""",
)
replace_once(
    consumer,
    """      canvasWidth={canvasWidth}\n      canvasHeight={canvasHeight}\n      stageScale={stageScale}\n""",
    """      canvasWidth={canvasWidth}\n      canvasHeight={canvasHeight}\n      canvasBackground={canvasBackground}\n      stageScale={stageScale}\n""",
)

# Focused fixture: add a deterministic NRGBA PNG over a non-black project
# background. The source carries hidden RGB at alpha=0 plus partial-alpha bands.
fixture = "backend/internal/video/parity_fixture_pixelate.go"
replace_once(
    fixture,
    """\tParityPixelateOpaqueFixtureName       = \"parity-pixelate-opaque-v1\"\n\tParityPixelateDecodedVideoFixtureName = \"parity-pixelate-decoded-video-v1\"\n""",
    """\tParityPixelateOpaqueFixtureName       = \"parity-pixelate-opaque-v1\"\n\tParityPixelateDecodedVideoFixtureName = \"parity-pixelate-decoded-video-v1\"\n\tParityPixelateAlphaFixtureName         = \"parity-pixelate-alpha-png-v1\"\n""",
)
replace_once(
    fixture,
    """func ParityPixelateOpaqueFixture() (TimelineDocument, []ParityFixtureAsset) {\n\treturn parityPixelateFixture(\n\t\tParityPixelateOpaqueFixtureName,\n\t\tparityPixelateOpaqueCanvasWidth,\n\t\tparityPixelateOpaqueCanvasHeight,\n\t\t\"asset-square\",\n\t\tParityFixtureAsset{ID: \"asset-square\", Kind: \"image\", Width: 512, Height: 512, DurationMS: parityPixelateDurationMS, Description: \"opaque 512x512 deterministic PNG\"},\n\t\t\"Opaque pixelate source\",\n\t)\n}\n\n// ParityPixelateDecodedVideoFixture keeps the same static pixelate semantics but\n// replaces the lossless PNG control with the deterministic H.264/yuv420p source\n// generated by video-parity-fixture. Matching the canvas to the source's\n// 640x360 dimensions avoids an unrelated media-resize variable so retained\n// differences isolate browser/FFmpeg decode and RGB color-conversion behavior.\nfunc ParityPixelateDecodedVideoFixture() (TimelineDocument, []ParityFixtureAsset) {\n\treturn parityPixelateFixture(\n\t\tParityPixelateDecodedVideoFixtureName,\n\t\tparityPixelateDecodedCanvasWidth,\n\t\tparityPixelateDecodedCanvasHeight,\n\t\t\"asset-landscape\",\n\t\tParityFixtureAsset{ID: \"asset-landscape\", Kind: \"video\", Width: 640, Height: 360, DurationMS: 24000, Description: \"deterministic H.264 yuv420p testsrc2 landscape video with stereo tone\"},\n\t\t\"Decoded H.264 pixelate source\",\n\t)\n}\n\nfunc parityPixelateFixture(name string, canvasWidth, canvasHeight int, assetID string, sourceAsset ParityFixtureAsset, sourceTrackName string) (TimelineDocument, []ParityFixtureAsset) {\n\tdoc := NewEmptyTimeline(canvasWidth, canvasHeight, parityPixelateFPS)\n\tdoc.DurationMS = parityPixelateDurationMS\n\tdoc.Canvas.Background = \"#000000\"\n""",
    """func ParityPixelateOpaqueFixture() (TimelineDocument, []ParityFixtureAsset) {\n\treturn parityPixelateFixture(\n\t\tParityPixelateOpaqueFixtureName,\n\t\tparityPixelateOpaqueCanvasWidth,\n\t\tparityPixelateOpaqueCanvasHeight,\n\t\t\"#000000\",\n\t\t\"asset-square\",\n\t\tParityFixtureAsset{ID: \"asset-square\", Kind: \"image\", Width: 512, Height: 512, DurationMS: parityPixelateDurationMS, Description: \"opaque 512x512 deterministic PNG\"},\n\t\t\"Opaque pixelate source\",\n\t)\n}\n\n// ParityPixelateDecodedVideoFixture keeps the same static pixelate semantics but\n// replaces the lossless PNG control with the deterministic H.264/yuv420p source\n// generated by video-parity-fixture. Matching the canvas to the source's\n// 640x360 dimensions avoids an unrelated media-resize variable so retained\n// differences isolate browser/FFmpeg decode and RGB color-conversion behavior.\nfunc ParityPixelateDecodedVideoFixture() (TimelineDocument, []ParityFixtureAsset) {\n\treturn parityPixelateFixture(\n\t\tParityPixelateDecodedVideoFixtureName,\n\t\tparityPixelateDecodedCanvasWidth,\n\t\tparityPixelateDecodedCanvasHeight,\n\t\t\"#000000\",\n\t\t\"asset-landscape\",\n\t\tParityFixtureAsset{ID: \"asset-landscape\", Kind: \"video\", Width: 640, Height: 360, DurationMS: 24000, Description: \"deterministic H.264 yuv420p testsrc2 landscape video with stereo tone\"},\n\t\t\"Decoded H.264 pixelate source\",\n\t)\n}\n\n// ParityPixelateAlphaFixture exercises the exact source-over order used by the\n// renderer: opaque project background, straight-alpha PNG media, then pixelate.\n// The generated PNG deliberately includes hidden RGB under alpha=0 plus several\n// partial-alpha bands so a premultiplication or compositing-order mistake is\n// visible in the retained pixelate region.\nfunc ParityPixelateAlphaFixture() (TimelineDocument, []ParityFixtureAsset) {\n\treturn parityPixelateFixture(\n\t\tParityPixelateAlphaFixtureName,\n\t\tparityPixelateOpaqueCanvasWidth,\n\t\tparityPixelateOpaqueCanvasHeight,\n\t\t\"#19324A\",\n\t\t\"asset-alpha\",\n\t\tParityFixtureAsset{ID: \"asset-alpha\", Kind: \"image\", Width: 512, Height: 512, DurationMS: parityPixelateDurationMS, Description: \"deterministic NRGBA PNG with hidden RGB and 0/64/128/192/255 alpha\"},\n\t\t\"Partial-alpha PNG pixelate source\",\n\t)\n}\n\nfunc parityPixelateFixture(name string, canvasWidth, canvasHeight int, background, assetID string, sourceAsset ParityFixtureAsset, sourceTrackName string) (TimelineDocument, []ParityFixtureAsset) {\n\tdoc := NewEmptyTimeline(canvasWidth, canvasHeight, parityPixelateFPS)\n\tdoc.DurationMS = parityPixelateDurationMS\n\tdoc.Canvas.Background = background\n""",
)
replace_once(
    fixture,
    """// ParityPixelateDecodedVideoFrameSamples binds the same canonical output-frame\n// identities while making the changing codec-decoded source explicit in names.\nfunc ParityPixelateDecodedVideoFrameSamples() []ParityFrameSample {\n\treturn parityPixelateFrameSamples(\"pixelate-video\")\n}\n\nfunc parityPixelateFrameSamples(prefix string) []ParityFrameSample {\n""",
    """// ParityPixelateDecodedVideoFrameSamples binds the same canonical output-frame\n// identities while making the changing codec-decoded source explicit in names.\nfunc ParityPixelateDecodedVideoFrameSamples() []ParityFrameSample {\n\treturn parityPixelateFrameSamples(\"pixelate-video\")\n}\n\n// ParityPixelateAlphaFrameSamples repeats the static alpha composition at the\n// same canonical frame identities used by the other focused pixelate controls.\nfunc ParityPixelateAlphaFrameSamples() []ParityFrameSample {\n\treturn parityPixelateFrameSamples(\"pixelate-alpha\")\n}\n\nfunc parityPixelateFrameSamples(prefix string) []ParityFrameSample {\n""",
)
replace_once(
    fixture,
    """// ParityPixelateDecodedVideoRegionBounds mirrors the same placement semantics on\n// the 640x360 decoded-video canvas without introducing source rescaling.\nfunc ParityPixelateDecodedVideoRegionBounds() ParityBounds {\n\treturn parityPixelateRegionBounds(parityPixelateDecodedCanvasWidth, parityPixelateDecodedCanvasHeight)\n}\n\nfunc parityPixelateRegionBounds(canvasWidth, canvasHeight int) ParityBounds {\n""",
    """// ParityPixelateDecodedVideoRegionBounds mirrors the same placement semantics on\n// the 640x360 decoded-video canvas without introducing source rescaling.\nfunc ParityPixelateDecodedVideoRegionBounds() ParityBounds {\n\treturn parityPixelateRegionBounds(parityPixelateDecodedCanvasWidth, parityPixelateDecodedCanvasHeight)\n}\n\n// ParityPixelateAlphaRegionBounds shares the 512x512 structural rectangle with\n// the lossless opaque control while changing only source alpha/background.\nfunc ParityPixelateAlphaRegionBounds() ParityBounds {\n\treturn parityPixelateRegionBounds(parityPixelateOpaqueCanvasWidth, parityPixelateOpaqueCanvasHeight)\n}\n\nfunc parityPixelateRegionBounds(canvasWidth, canvasHeight int) ParityBounds {\n""",
)
replace_once(
    fixture,
    """// ParityPixelateDecodedVideoRegionFrames binds the decoded-video measurement\n// region to exact frame identity. The tolerant codec report consumes these\n// bounds without weakening the lossless structural-exactness policy.\nfunc ParityPixelateDecodedVideoRegionFrames(samples []ParityFrameSample) []ParityFixtureRegionFrame {\n\treturn parityPixelateRegionFrames(samples, ParityPixelateDecodedVideoRegionBounds())\n}\n\nfunc parityPixelateRegionFrames(samples []ParityFrameSample, bounds ParityBounds) []ParityFixtureRegionFrame {\n""",
    """// ParityPixelateDecodedVideoRegionFrames binds the decoded-video measurement\n// region to exact frame identity. The tolerant codec report consumes these\n// bounds without weakening the lossless structural-exactness policy.\nfunc ParityPixelateDecodedVideoRegionFrames(samples []ParityFrameSample) []ParityFixtureRegionFrame {\n\treturn parityPixelateRegionFrames(samples, ParityPixelateDecodedVideoRegionBounds())\n}\n\n// ParityPixelateAlphaRegionFrames binds source-over alpha composition evidence\n// to the same exact 403x307 region policy as the lossless PNG control.\nfunc ParityPixelateAlphaRegionFrames(samples []ParityFrameSample) []ParityFixtureRegionFrame {\n\treturn parityPixelateRegionFrames(samples, ParityPixelateAlphaRegionBounds())\n}\n\nfunc parityPixelateRegionFrames(samples []ParityFrameSample, bounds ParityBounds) []ParityFixtureRegionFrame {\n""",
)

# Unit coverage for the alpha fixture and its frame-indexed region policy.
tests = "backend/internal/video/parity_fixture_pixelate_test.go"
replace_once(
    tests,
    """func TestParityPixelateDecodedVideoFixtureIsValidAndUnscaled(t *testing.T) {\n\tdoc, assets := ParityPixelateDecodedVideoFixture()\n\tvalidated, err := ValidateTimelineDocument(doc)\n\tif err != nil {\n\t\tt.Fatalf(\"ValidateTimelineDocument() error = %v\", err)\n\t}\n\tif validated.Canvas.Width != 640 || validated.Canvas.Height != 360 || validated.Canvas.FPS != 30 {\n\t\tt.Fatalf(\"canvas = %dx%d@%d, want 640x360@30\", validated.Canvas.Width, validated.Canvas.Height, validated.Canvas.FPS)\n\t}\n\tif validated.DurationMS != 2000 {\n\t\tt.Fatalf(\"duration_ms = %d, want 2000\", validated.DurationMS)\n\t}\n\tif len(assets) != 2 || assets[0].ID != \"asset-landscape\" || assets[0].Kind != \"video\" || assets[0].Width != 640 || assets[0].Height != 360 || assets[1].ID != \"asset-audio\" {\n\t\tt.Fatalf(\"assets = %#v, want 640x360 video plus audio harness asset\", assets)\n\t}\n\tassertIsolatedPixelateFixture(t, validated)\n}\n""",
    """func TestParityPixelateDecodedVideoFixtureIsValidAndUnscaled(t *testing.T) {\n\tdoc, assets := ParityPixelateDecodedVideoFixture()\n\tvalidated, err := ValidateTimelineDocument(doc)\n\tif err != nil {\n\t\tt.Fatalf(\"ValidateTimelineDocument() error = %v\", err)\n\t}\n\tif validated.Canvas.Width != 640 || validated.Canvas.Height != 360 || validated.Canvas.FPS != 30 {\n\t\tt.Fatalf(\"canvas = %dx%d@%d, want 640x360@30\", validated.Canvas.Width, validated.Canvas.Height, validated.Canvas.FPS)\n\t}\n\tif validated.DurationMS != 2000 {\n\t\tt.Fatalf(\"duration_ms = %d, want 2000\", validated.DurationMS)\n\t}\n\tif len(assets) != 2 || assets[0].ID != \"asset-landscape\" || assets[0].Kind != \"video\" || assets[0].Width != 640 || assets[0].Height != 360 || assets[1].ID != \"asset-audio\" {\n\t\tt.Fatalf(\"assets = %#v, want 640x360 video plus audio harness asset\", assets)\n\t}\n\tassertIsolatedPixelateFixture(t, validated)\n}\n\nfunc TestParityPixelateAlphaFixtureIsValidAndUsesNonBlackBackground(t *testing.T) {\n\tdoc, assets := ParityPixelateAlphaFixture()\n\tvalidated, err := ValidateTimelineDocument(doc)\n\tif err != nil {\n\t\tt.Fatalf(\"ValidateTimelineDocument() error = %v\", err)\n\t}\n\tif validated.Canvas.Width != 512 || validated.Canvas.Height != 512 || validated.Canvas.FPS != 30 {\n\t\tt.Fatalf(\"canvas = %dx%d@%d, want 512x512@30\", validated.Canvas.Width, validated.Canvas.Height, validated.Canvas.FPS)\n\t}\n\tif validated.Canvas.Background != \"#19324A\" {\n\t\tt.Fatalf(\"background = %q, want #19324A\", validated.Canvas.Background)\n\t}\n\tif len(assets) != 2 || assets[0].ID != \"asset-alpha\" || assets[0].Kind != \"image\" || assets[0].Width != 512 || assets[0].Height != 512 || assets[1].ID != \"asset-audio\" {\n\t\tt.Fatalf(\"assets = %#v, want alpha PNG plus audio harness asset\", assets)\n\t}\n\tassertIsolatedPixelateFixture(t, validated)\n}\n""",
)
replace_once(
    tests,
    """func TestParityPixelateDecodedVideoSamplesAndRegionsStayFrameBound(t *testing.T) {\n\tsamples := ParityPixelateDecodedVideoFrameSamples()\n\twantFrames := []int64{0, 15, 30, 59}\n\tassertPixelateFrames(t, samples, wantFrames)\n\n\tbounds := ParityPixelateDecodedVideoRegionBounds()\n\twantBounds := (ParityBounds{MinX: 135, MinY: 18, MaxX: 538, MaxY: 325})\n\tif bounds != wantBounds {\n\t\tt.Fatalf(\"bounds = %#v, want %#v\", bounds, wantBounds)\n\t}\n\tassertPixelateRegionFrames(t, samples, bounds, ParityPixelateDecodedVideoRegionFrames(samples))\n}\n""",
    """func TestParityPixelateDecodedVideoSamplesAndRegionsStayFrameBound(t *testing.T) {\n\tsamples := ParityPixelateDecodedVideoFrameSamples()\n\twantFrames := []int64{0, 15, 30, 59}\n\tassertPixelateFrames(t, samples, wantFrames)\n\n\tbounds := ParityPixelateDecodedVideoRegionBounds()\n\twantBounds := (ParityBounds{MinX: 135, MinY: 18, MaxX: 538, MaxY: 325})\n\tif bounds != wantBounds {\n\t\tt.Fatalf(\"bounds = %#v, want %#v\", bounds, wantBounds)\n\t}\n\tassertPixelateRegionFrames(t, samples, bounds, ParityPixelateDecodedVideoRegionFrames(samples))\n}\n\nfunc TestParityPixelateAlphaSamplesAndRegionsStayFrameBound(t *testing.T) {\n\tsamples := ParityPixelateAlphaFrameSamples()\n\twantFrames := []int64{0, 15, 30, 59}\n\tassertPixelateFrames(t, samples, wantFrames)\n\n\tbounds := ParityPixelateAlphaRegionBounds()\n\twantBounds := (ParityBounds{MinX: 71, MinY: 94, MaxX: 474, MaxY: 401})\n\tif bounds != wantBounds {\n\t\tt.Fatalf(\"bounds = %#v, want %#v\", bounds, wantBounds)\n\t}\n\tassertPixelateRegionFrames(t, samples, bounds, ParityPixelateAlphaRegionFrames(samples))\n}\n""",
)

# CLI fixture variant.
cmd = "backend/cmd/video-pixelate-parity-fixture/main.go"
replace_once(cmd, 'variant := flag.String("variant", "opaque-png", "fixture variant: opaque-png or decoded-video")', 'variant := flag.String("variant", "opaque-png", "fixture variant: opaque-png, decoded-video, or alpha-png")')
replace_once(
    cmd,
    """\tcase \"decoded-video\":\n\t\tname = video.ParityPixelateDecodedVideoFixtureName\n\t\tdoc, assets = video.ParityPixelateDecodedVideoFixture()\n\t\tsamples = video.ParityPixelateDecodedVideoFrameSamples()\n\t\tframes = video.ParityPixelateDecodedVideoRegionFrames(samples)\n\tdefault:\n\t\texitf(\"unknown --variant %q (want opaque-png or decoded-video)\", *variant)\n""",
    """\tcase \"decoded-video\":\n\t\tname = video.ParityPixelateDecodedVideoFixtureName\n\t\tdoc, assets = video.ParityPixelateDecodedVideoFixture()\n\t\tsamples = video.ParityPixelateDecodedVideoFrameSamples()\n\t\tframes = video.ParityPixelateDecodedVideoRegionFrames(samples)\n\tcase \"alpha-png\":\n\t\tname = video.ParityPixelateAlphaFixtureName\n\t\tdoc, assets = video.ParityPixelateAlphaFixture()\n\t\tsamples = video.ParityPixelateAlphaFrameSamples()\n\t\tframes = video.ParityPixelateAlphaRegionFrames(samples)\n\tdefault:\n\t\texitf(\"unknown --variant %q (want opaque-png, decoded-video, or alpha-png)\", *variant)\n""",
)

# Deterministic source media generation: standard-library NRGBA preserves hidden
# straight RGB under alpha=0 without relying on FFmpeg's pixel-format negotiation.
generator = "backend/cmd/video-parity-fixture/main.go"
replace_once(
    generator,
    """import (\n\t\"encoding/json\"\n\t\"flag\"\n\t\"fmt\"\n\t\"os\"\n\t\"os/exec\"\n\t\"path/filepath\"\n""",
    """import (\n\t\"encoding/json\"\n\t\"flag\"\n\t\"fmt\"\n\t\"image\"\n\t\"image/color\"\n\t\"image/png\"\n\t\"os\"\n\t\"os/exec\"\n\t\"path/filepath\"\n""",
)
replace_once(
    generator,
    """\tfor _, args := range commands {\n\t\tfull := append([]string{\"-hide_banner\", \"-loglevel\", \"error\", \"-y\"}, args...)\n\t\tcmd := exec.Command(ffmpeg, full...)\n\t\tif output, err := cmd.CombinedOutput(); err != nil {\n\t\t\treturn fmt.Errorf(\"%v: %w: %s\", args, err, output)\n\t\t}\n\t}\n\treturn nil\n}\n\nfunc exitf(format string, args ...any) { fmt.Fprintf(os.Stderr, format+\"\\n\", args...); os.Exit(1) }\n""",
    """\tfor _, args := range commands {\n\t\tfull := append([]string{\"-hide_banner\", \"-loglevel\", \"error\", \"-y\"}, args...)\n\t\tcmd := exec.Command(ffmpeg, full...)\n\t\tif output, err := cmd.CombinedOutput(); err != nil {\n\t\t\treturn fmt.Errorf(\"%v: %w: %s\", args, err, output)\n\t\t}\n\t}\n\tif err := writeAlphaFixturePNG(filepath.Join(mediaDir, \"asset-alpha.png\")); err != nil {\n\t\treturn fmt.Errorf(\"generate alpha PNG: %w\", err)\n\t}\n\treturn nil\n}\n\nfunc writeAlphaFixturePNG(path string) error {\n\timg := image.NewNRGBA(image.Rect(0, 0, 512, 512))\n\talphaBands := [...]uint8{0, 64, 128, 192, 255}\n\tfor y := 0; y < 512; y++ {\n\t\tfor x := 0; x < 512; x++ {\n\t\t\talpha := alphaBands[((x / 64) + (y / 64))%len(alphaBands)]\n\t\t\t// Keep RGB deliberately non-zero and spatially varying even when\n\t\t\t// alpha is zero. Correct source-over composition must discard those\n\t\t\t// hidden channels instead of leaking them into the project background.\n\t\t\tpixel := color.NRGBA{\n\t\t\t\tR: uint8((x*37 + y*17 + 91) & 0xff),\n\t\t\t\tG: uint8((x*11 + y*29 + 53) & 0xff),\n\t\t\t\tB: uint8((x*23 + y*7 + 211) & 0xff),\n\t\t\t\tA: alpha,\n\t\t\t}\n\t\t\timg.SetNRGBA(x, y, pixel)\n\t\t}\n\t}\n\tfile, err := os.Create(path)\n\tif err != nil {\n\t\treturn err\n\t}\n\tdefer file.Close()\n\tencoder := png.Encoder{CompressionLevel: png.BestCompression}\n\treturn encoder.Encode(file, img)\n}\n\nfunc exitf(format string, args ...any) { fmt.Fprintf(os.Stderr, format+\"\\n\", args...); os.Exit(1) }\n""",
)

# Capture harness knows the new deterministic asset recipe.
capture = "scripts/video-parity-capture.mjs"
replace_once(
    capture,
    """    'asset-square': ['asset-square.png', 'image/png'],\n    'asset-audio': ['asset-audio.wav', 'audio/wav'],\n""",
    """    'asset-square': ['asset-square.png', 'image/png'],\n    'asset-alpha': ['asset-alpha.png', 'image/png'],\n    'asset-audio': ['asset-audio.wav', 'audio/wav'],\n""",
)

# Runtime helper comment: the alpha proof is now explicitly a video-only
# readiness/opacity safeguard; image alpha is resolved by composed-backdrop order.
runtime = "frontend/src/components/video/previewPixelateCanvasRuntime.ts"
replace_once(
    runtime,
    "/** Prove every decoded pixel in one candidate backdrop region has straight alpha 255. */",
    "/** Prove every decoded source pixel in one video candidate region has straight alpha 255. */",
)
replace_once(
    runtime,
    """ * Classify one opacity proof attempt. A newly sought HTMLVideoElement can report\n * HAVE_CURRENT_DATA before Chromium has made that decoded frame rasterizable to\n * Canvas, so an initial non-opaque read is not sufficient evidence of authored\n * transparency. Video consumers may retry for a caller-bounded number of paint\n * frames; images and exhausted video retries still fail closed to compatibility\n * rendering. The proof itself remains exact: only alpha 255 reaches ready.\n""",
    """ * Classify one decoded-video opacity/readiness proof attempt. A newly sought\n * HTMLVideoElement can report HAVE_CURRENT_DATA before Chromium has made that\n * decoded frame rasterizable to Canvas, so an initial non-opaque read is not\n * sufficient evidence of authored transparency. Video consumers may retry for a\n * caller-bounded number of paint frames; exhausted retries still fail closed.\n * Images do not use this proof once their source-over project-background\n * composition is authoritative. The proof itself remains exact: only alpha 255\n * reaches ready.\n""",
)

# Durable tracker: record #293 as the exact-head merge and #294 as current alpha work.
plan = "docs/VIDEO_EDIT_STUDIO_WYSIWYG_RENDERING_IMPLEMENTATION_PLAN_2026-08.md"
replace_once(plan, "**Last updated:** 2026-08-29", "**Last updated:** 2026-08-30")
replace_once(
    plan,
    """Latest merged WYSIWYG program PR: **#291 — Merge validated codec-decoded pixelate parity evidence** — squash merge `7d5f36c3230d23eef46de310d6ac785b1b998c33` (2026-08-29). #291 contains the exact validated head from draft #290; #290 was closed only because the connector's ready-for-review mutation failed against GitHub's current GraphQL schema.\n\nCurrent implementation PR: **#292 — Prove deterministic decoded-video frame identity** on branch `fix/video-wysiwyg-phase3-decoded-frame-identity`, created directly from #291's actual squash result `7d5f36c3230d23eef46de310d6ac785b1b998c33`.\n""",
    f"""Latest merged WYSIWYG program PR: **#293 — Merge validated decoded-video frame identity** — squash merge `{PARENT}` (2026-08-30). #293 points at the exact validated head from draft #292; #292 was closed only because GitHub still refused to merge the draft through the connector.\n\nCurrent implementation PR: **#{PR} — Compose pixelate alpha sources over canonical background** on branch `fix/video-wysiwyg-phase3-pixelate-alpha-composition`, created directly from #293's actual squash result `{PARENT}`.\n""",
)
replace_once(plan, "### #292 current scope", "### #293 merged decoded-frame identity")
replace_once(
    plan,
    """- Preserve the original 103-sample longitudinal baseline and transparent/premultiplied-alpha deferral. Final tracker-bearing merge validation must still pass the complete exact-head Quality, Security, Pixelate Evidence, and platform/sandbox workflow set.\n\n## Phase tracker\n""",
    f"""- Preserve the original 103-sample longitudinal baseline and transparent/premultiplied-alpha deferral. Final tracker-bearing head `f255243bc36da8d13efaf55ee770b4f20503723d` passed Quality #1716, Security #1721, Video Pixelate Parity Evidence #45, Chromium smoke, the full renderer parity baseline, and all applicable platform/sandbox assurances. #293 squash-merged that exact validated tree as `{PARENT}`.\n\n### #{PR} current scope\n\n#{PR} closes the first transparent-image pixelate composition gap without broadening canonical authored semantics:\n\n- Mirror FFmpeg's admitted renderer order for the one-media-layer pixelate path: start from the opaque project canvas background, source-over the decoded media through canonical media geometry, then sample/pixelate the already-composited RGB backdrop.\n- Match the renderer's background grammar exactly: six-digit RGB with or without `#`; anything else falls back to black.\n- Admit transparent and partial-alpha **images** by Canvas source-over composition. Do not inspect, unpremultiply, or reinterpret image source bytes. Hidden RGB under alpha `0` must never leak into the composed backdrop.\n- Keep decoded-video source-only alpha/readiness proof unchanged before background composition. Transparent video remains fail-closed in this slice because the existing proof also guards Chromium's post-seek rasterizability race.\n- Add deterministic `parity-pixelate-alpha-png-v1` evidence over non-black `#19324A`, using an NRGBA PNG with hidden RGB and alpha `0/64/128/192/255`, the established `403x307` region/block-20 raster, and frames `0/15/30/59`.\n- Preserve #289's byte-exact opaque-PNG gate and #293's H.264 requested/presented frame-identity plus focused ±3 RGB gate as independent controls.\n\n## Phase tracker\n""",
)
replace_once(
    plan,
    "| Phase 0 — Reproducible parity baseline | **In progress** | Deterministic 103-frame visual/audio/delivery evidence exists. #266 merged fail-closed frame-indexed region-policy inputs. #289 added the byte-exact opaque-PNG gate; #291 merged retained H.264 decoded-video measurement. #292 implementation evidence now proves decoded frame identity on 0/15/30/59 and enforces the focused ±3 H.264/yuv420p color envelope only after that identity proof. Resource-font fixture coverage and second-platform retained evidence remain. |",
    f"| Phase 0 — Reproducible parity baseline | **In progress** | Deterministic 103-frame visual/audio/delivery evidence exists. #289 added the byte-exact opaque-PNG gate; #291 added H.264 measurement; #293 proves decoded frame identity on 0/15/30/59 and gates the focused ±3 H.264/yuv420p envelope only after identity proof. #{PR} adds a deterministic partial-alpha PNG/background-composition control. Resource-font fixture coverage and second-platform retained evidence remain. |",
)
replace_once(
    plan,
    "| Phase 3 — Shared preview composition | **In progress** | #261–#289 merged deterministic activity/source/transform/view/perspective/media geometry/effects/transitions, canonical text/shape/cursor painters, exact browser font readiness, Chromium text-layout snapshots, deterministic pixelate raster/backdrop semantics, runtime-proven opaque Canvas consumption, byte-exact opaque-PNG evidence, and sampled-render source fan-out. #291 extends retained evidence to decoded H.264; #292 implementation evidence closes deterministic decoded-video frame identity while preserving fail-closed alpha behavior. Transparent-alpha semantics, weighted-raster broadening, normal-playback canonicalization, diagnostics/rollback, and audio consumption remain. |",
    f"| Phase 3 — Shared preview composition | **In progress** | #261–#289 merged deterministic activity/source/transform/view/perspective/media geometry/effects/transitions, canonical text/shape/cursor painters, font readiness/layout snapshots, deterministic pixelate semantics, exact opaque-PNG evidence, and sampled-render fan-out. #291/#293 close retained H.264 measurement and deterministic frame identity. #{PR} implements renderer-ordered project-background/source-over composition for transparent images while keeping transparent video fail-closed. Weighted-raster broadening, normal-playback canonicalization, diagnostics/rollback, and audio consumption remain. |",
)
replace_once(
    plan,
    "| #291 | Retained H.264 decoded-video pixelate evidence and bounded video Canvas readiness | `7d5f36c3230d23eef46de310d6ac785b1b998c33` |",
    f"| #291 | Retained H.264 decoded-video pixelate evidence and bounded video Canvas readiness | `7d5f36c3230d23eef46de310d6ac785b1b998c33` |\n| #293 | Deterministic decoded-video frame identity and focused ±3 H.264 pixelate gate | `{PARENT}` |",
)
replace_once(
    plan,
    "Recent lineage: #284 from #283 squash `3543ddf7...`; #285 from #284 `7884fef8...`; #286 from #285 `64e34450...`; #287 from #286 `40e895ee...`; #288 from #287 `2774ee76...`; #289 from #288 `7be8e86f...`; #290 validated directly from #289 squash `86dc6a6eaa4eb5f494f8d935f5535da8fb517b0b`; #291 mirrored that exact validated #290 head because the ready-for-review connector mutation failed, then squash-merged as `7d5f36c3230d23eef46de310d6ac785b1b998c33`; **#292 is directly from #291 squash `7d5f36c3230d23eef46de310d6ac785b1b998c33`**.",
    f"Recent lineage: #284 from #283 squash `3543ddf7...`; #285 from #284 `7884fef8...`; #286 from #285 `64e34450...`; #287 from #286 `40e895ee...`; #288 from #287 `2774ee76...`; #289 from #288 `7be8e86f...`; #290 validated from #289 squash; #291 mirrored that exact validated #290 head and merged as `7d5f36c3...`; #292 validated directly from #291; #293 mirrored exact validated #292 head and squash-merged as `{PARENT}`; **#{PR} is directly from #293 squash `{PARENT}`**.",
)
replace_once(
    plan,
    "The focused `parity-pixelate-opaque-v1` fixture is a byte-exact non-regression gate for the isolated opaque-PNG static pixelate path. `parity-pixelate-decoded-video-v1` is additive decoded-media evidence: #292 proves deterministic decoded-frame identity first and then applies the explicit ±3 RGB H.264/yuv420p pixelate-region envelope without changing repository-global parity defaults.",
    f"The focused `parity-pixelate-opaque-v1` fixture is a byte-exact non-regression gate for the isolated opaque-PNG static pixelate path. `parity-pixelate-decoded-video-v1` is additive decoded-media evidence: #293 proves deterministic decoded-frame identity first and then applies the explicit ±3 RGB H.264/yuv420p pixelate-region envelope without changing repository-global parity defaults. `parity-pixelate-alpha-png-v1` is #{PR}'s additive straight-alpha/source-over project-background control.",
)
replace_once(
    plan,
    "| Pixelate raster math is confused with backdrop-source parity | #285 owns grid/sample-index math; #286 owns structural backdrop admission; #287 owns FFmpeg scaler selection; #288 owns browser runtime acquisition/opaque proof; #289 owns byte-exact PNG evidence; #291 owns decoded-video measurement; #292 owns decoded-frame identity and the focused codec/color acceptance gate. None is substituted for another. |",
    f"| Pixelate raster math is confused with backdrop-source parity | #285 owns grid/sample-index math; #286 owns structural admission; #287 owns FFmpeg scaler selection; #288 owns runtime acquisition; #289 owns byte-exact PNG evidence; #291 owns decoded-video measurement; #293 owns decoded-frame identity/codec acceptance; #{PR} owns project-background/source-over image-alpha composition. None is substituted for another. |",
)
replace_once(
    plan,
    "| MIME type or codec is treated as proof of an opaque backdrop | #288/#291 scan the sampled RGBA target rectangle and activate exact Canvas only when every alpha byte is `255`; no MIME-only or codec-only shortcut exists. |",
    f"| MIME type or codec is treated as proof of an opaque backdrop | #{PR} does not infer image opacity from MIME: images are source-over composited onto the renderer-matched opaque project background. Decoded video still requires the exact source-only alpha/readiness proof; no MIME/codec shortcut exists. |",
)
replace_once(
    plan,
    "| Browser seek lands on a neighboring decoded frame at an exact boundary | #291 retained frame 59 as timing debt. #292 implementation evidence applies a 0.25 ms-or-smaller video-only boundary nudge and proves `requestVideoFrameCallback` presents the requested 0/15/30/59 frames before the ±3 codec/color gate is accepted. |",
    "| Browser seek lands on a neighboring decoded frame at an exact boundary | #291 retained frame 59 as timing debt. #293 applies the 0.25 ms-or-smaller video-only boundary nudge and proves `requestVideoFrameCallback` presents requested 0/15/30/59 before the ±3 codec/color gate is accepted. |",
)
replace_once(
    plan,
    "| Alpha/pixel-format conversion is assumed byte-identical across browser and FFmpeg | Transparent-source execution stays deferred until decoded RGBA/premultiplication/compositing semantics are defined and retained. |",
    f"| Alpha/pixel-format conversion is assumed byte-identical across browser and FFmpeg | #{PR} mirrors renderer order for transparent images by compositing the decoded image over the canonical opaque project background before pixelate; the NRGBA fixture carries hidden RGB and partial alpha specifically to catch premultiplication/source-over mistakes. Transparent video remains deferred. |",
)
replace_once(
    plan,
    "| Codec-noisy decoded equality is treated as structural parity | PNG structural exactness remains independent; #292 gates decoded-video color at ±3 only after source-frame identity is proven, while repository-default ±2 diagnostics remain unchanged. |",
    "| Codec-noisy decoded equality is treated as structural parity | PNG structural exactness remains independent; #293 gates decoded-video color at ±3 only after source-frame identity is proven, while repository-default ±2 diagnostics remain unchanged. |",
)
replace_once(
    plan,
    """1. **Finish and merge #292 after the tracker-bearing exact-head workflow wave is green.** The implementation evidence already proves requested/presented decoded frame identity on 0/15/30/59 and a 100% pixel pass at the focused ±3 H.264/yuv420p envelope, while the byte-exact PNG control remains independent.\n2. **Next slice: define transparent/premultiplied-alpha pixelate semantics.** Keep current fail-closed behavior until canonical decoded RGBA representation, browser Canvas premultiplication, FFmpeg alpha handling, and source-over compositing order are explicit and cross-runtime testable.\n3. Add a deterministic transparent/partial-alpha fixture with retained browser↔renderer region evidence. Do not infer opacity or compositing semantics from MIME type, codec, or container.\n4. Broaden pixelate and weighted-Canvas raster eligibility only after each additional painter/source has exact composition semantics and retained evidence; preserve the opaque PNG and H.264 controls as independent non-regression gates.\n5. Add resource-font fixture coverage and retain parity evidence on a second supported OS/FFmpeg environment before calling cross-machine Phase 0 visual identity closed.\n6. Continue Phase 3 with normal-playback canonicalization, explicit diagnostics/rollback, then shared AudioGraph consumption.\n""",
    f"""1. **Execute #{PR}: transparent-image project-background composition.** Retain alpha PNG browser↔renderer region evidence proving hidden RGB under alpha `0` does not leak and partial-alpha pixels follow the same source-over result before pixelate.\n2. Keep transparent decoded video fail-closed until a reliable presentation/readiness proof can distinguish legitimate transparent decoded pixels from Chromium's post-seek not-yet-rasterizable state. Do not remove the H.264 source-only guard just to broaden alpha support.\n3. After #{PR} is retained and green, broaden pixelate/weighted-Canvas raster eligibility only for painter/source classes whose source-over ordering is explicit and independently evidenced.\n4. Add resource-font fixture coverage and retain parity evidence on a second supported OS/FFmpeg environment before calling cross-machine Phase 0 visual identity closed.\n5. Continue Phase 3 with normal-playback canonicalization, explicit diagnostics/rollback, then shared AudioGraph consumption.\n""",
)

print("PR 294 alpha patch applied")
