from pathlib import Path

path = Path('docs/VIDEO_EDIT_STUDIO_WYSIWYG_RENDERING_IMPLEMENTATION_PLAN_2026-08.md')
text = path.read_text(encoding='utf-8')

def replace_once(old: str, new: str) -> None:
    global text
    count = text.count(old)
    if count != 1:
        raise SystemExit(f'expected one match, found {count}: {old[:120]!r}')
    text = text.replace(old, new, 1)

replace_once(
"""- Only after frame identity passes, enforce the measured H.264/yuv420p codec/color envelope as an explicit `max_channel_delta <= 3` pixelate-region gate. Repository-global ±2/99.9% defaults and #289's byte-exact PNG gate remain unchanged.\n- Preserve the original 103-sample longitudinal baseline and transparent/premultiplied-alpha deferral.\n""",
"""- Only after frame identity passes, enforce the measured H.264/yuv420p codec/color envelope as an explicit `max_channel_delta <= 3` pixelate-region gate. Repository-global ±2/99.9% defaults and #289's byte-exact PNG gate remain unchanged.\n- Implementation head `f9a3a6baa05c1ec82d5453b77e95c909cc09d22d` passed Video Pixelate Parity Evidence #41. The decoded job and the independent opaque-PNG job both completed successfully.\n- Retained decoded artifact `9725989461` is 14,087,302 bytes with SHA-256 `1189464ee9067b55271bc507ce604843f258a338102481a84c2d53c435c6ed7f`; retained exact-PNG artifact `9725990152` is 8,632,756 bytes with SHA-256 `6e0d3a407e5ccedefa7f03f9a267d23cbdc53f9d9b3474c6dbf4f5c8d60962ea`.\n- Chromium presentation identity is now explicit: frame `0` retains the allowed initial-current-time proof at `0`; frame `15` presents `mediaTime=0.5` after seeking to `currentTime=0.50025`; frame `30` presents `mediaTime=1.0` after seeking to `currentTime=1.00025`; frame `59` presents `mediaTime=1.966667` after seeking to `currentTime=1.966916`. The requested/presented frame indices are `0/15/30/59` exactly.\n- Every corrected decoded pixelate region covers `[135,18)-[538,325)` = `123,721` pixels. All `123,721` pixels pass the focused ±3 RGB envelope on every sample and every sample has `max_channel_delta=3`. Frame `59`'s repository-default ±2 diagnostic improves from the pre-fix gross mismatch to `pixel_pass_rate=0.9967669191`, `SSIM=0.9999361828`, and `MAE=0.8941570146`, confirming the remaining difference is ordinary codec/color conversion rather than frame identity.\n- Preserve the original 103-sample longitudinal baseline and transparent/premultiplied-alpha deferral. Final tracker-bearing merge validation must still pass the complete exact-head Quality, Security, Pixelate Evidence, and platform/sandbox workflow set.\n"""
)

replace_once(
"| Phase 0 — Reproducible parity baseline | **In progress** | Deterministic 103-frame visual/audio/delivery evidence exists. #266 merged fail-closed frame-indexed region-policy inputs. #289 added the byte-exact opaque-PNG gate; #291 merged retained H.264 decoded-video evidence and isolated codec/color variation from the final-frame browser seek-boundary mismatch. #292 now closes decoded-frame identity and, only after that proof, promotes the measured ±3 channel envelope into a focused codec/color gate. Resource-font fixture coverage and second-platform retained evidence remain. |",
"| Phase 0 — Reproducible parity baseline | **In progress** | Deterministic 103-frame visual/audio/delivery evidence exists. #266 merged fail-closed frame-indexed region-policy inputs. #289 added the byte-exact opaque-PNG gate; #291 merged retained H.264 decoded-video measurement. #292 implementation evidence now proves decoded frame identity on 0/15/30/59 and enforces the focused ±3 H.264/yuv420p color envelope only after that identity proof. Resource-font fixture coverage and second-platform retained evidence remain. |"
)
replace_once(
"| Phase 3 — Shared preview composition | **In progress** | #261–#289 merged deterministic activity/source/transform/view/perspective/media geometry/effects/transitions, canonical text/shape/cursor painters, exact browser font readiness, Chromium text-layout snapshots, deterministic pixelate raster/backdrop semantics, runtime-proven opaque Canvas consumption, byte-exact opaque-PNG evidence, and sampled-render source fan-out. #291 extends retained evidence to decoded H.264 while preserving fail-closed alpha behavior; #292 addresses deterministic decoded-video frame identity. Transparent-alpha semantics, weighted-raster broadening, normal-playback canonicalization, diagnostics/rollback, and audio consumption remain. |",
"| Phase 3 — Shared preview composition | **In progress** | #261–#289 merged deterministic activity/source/transform/view/perspective/media geometry/effects/transitions, canonical text/shape/cursor painters, exact browser font readiness, Chromium text-layout snapshots, deterministic pixelate raster/backdrop semantics, runtime-proven opaque Canvas consumption, byte-exact opaque-PNG evidence, and sampled-render source fan-out. #291 extends retained evidence to decoded H.264; #292 implementation evidence closes deterministic decoded-video frame identity while preserving fail-closed alpha behavior. Transparent-alpha semantics, weighted-raster broadening, normal-playback canonicalization, diagnostics/rollback, and audio consumption remain. |"
)
replace_once(
"The focused `parity-pixelate-opaque-v1` fixture is a byte-exact non-regression gate for the isolated opaque-PNG static pixelate path. `parity-pixelate-decoded-video-v1` is additive decoded-media evidence and intentionally separates ordinary codec/color variation from deterministic decoded-frame-identity debt.",
"The focused `parity-pixelate-opaque-v1` fixture is a byte-exact non-regression gate for the isolated opaque-PNG static pixelate path. `parity-pixelate-decoded-video-v1` is additive decoded-media evidence: #292 proves deterministic decoded-frame identity first and then applies the explicit ±3 RGB H.264/yuv420p pixelate-region envelope without changing repository-global parity defaults."
)
replace_once(
"| Browser seek lands on a neighboring decoded frame at an exact boundary | #291 retains frame 59 as explicit timing evidence and excludes it from codec/color inference; #292 applies a sub-tolerance video-only boundary nudge and requires `requestVideoFrameCallback` evidence before the ±3 codec/color gate can pass. |",
"| Browser seek lands on a neighboring decoded frame at an exact boundary | #291 retained frame 59 as timing debt. #292 implementation evidence applies a 0.25 ms-or-smaller video-only boundary nudge and proves `requestVideoFrameCallback` presents the requested 0/15/30/59 frames before the ±3 codec/color gate is accepted. |"
)
replace_once(
"| Codec-noisy decoded equality is treated as structural parity | PNG structural exactness remains independent; decoded-video color thresholds apply only after source-frame identity is proven. |",
"| Codec-noisy decoded equality is treated as structural parity | PNG structural exactness remains independent; #292 gates decoded-video color at ±3 only after source-frame identity is proven, while repository-default ±2 diagnostics remain unchanged. |"
)
replace_once(
"""1. **Execute #292: deterministic decoded-video frame identity.** Retain browser `requestVideoFrameCallback` timestamps and require canonical frames 0/15/30/59 to present the same decoded frame identity after the sub-tolerance boundary-safe seek.\n2. In the same focused gate, accept H.264/yuv420p browser↔FFmpeg pixelate-region color variation only when every channel delta is ≤3 **after** frame identity passes. Keep repository-global ±2/99.9% diagnostics unchanged so this codec-specific evidence does not silently redefine other parity classes.\n3. Keep #289's opaque-PNG exactness unchanged as the zero-tolerance non-regression control and keep the 103-frame `parity-torture-v1` baseline additive and longitudinal.\n4. Keep transparent/premultiplied-alpha sources deferred until decoded RGBA, premultiplication, and compositing semantics are explicitly defined and retained.\n5. Broaden pixelate and weighted-Canvas raster eligibility only after each additional painter/source has exact composition semantics and retained evidence.\n6. Continue Phase 3 with normal-playback canonicalization, explicit diagnostics/rollback, then shared AudioGraph consumption.\n""",
"""1. **Finish and merge #292 after the tracker-bearing exact-head workflow wave is green.** The implementation evidence already proves requested/presented decoded frame identity on 0/15/30/59 and a 100% pixel pass at the focused ±3 H.264/yuv420p envelope, while the byte-exact PNG control remains independent.\n2. **Next slice: define transparent/premultiplied-alpha pixelate semantics.** Keep current fail-closed behavior until canonical decoded RGBA representation, browser Canvas premultiplication, FFmpeg alpha handling, and source-over compositing order are explicit and cross-runtime testable.\n3. Add a deterministic transparent/partial-alpha fixture with retained browser↔renderer region evidence. Do not infer opacity or compositing semantics from MIME type, codec, or container.\n4. Broaden pixelate and weighted-Canvas raster eligibility only after each additional painter/source has exact composition semantics and retained evidence; preserve the opaque PNG and H.264 controls as independent non-regression gates.\n5. Add resource-font fixture coverage and retain parity evidence on a second supported OS/FFmpeg environment before calling cross-machine Phase 0 visual identity closed.\n6. Continue Phase 3 with normal-playback canonicalization, explicit diagnostics/rollback, then shared AudioGraph consumption.\n"""
)

path.write_text(text, encoding='utf-8')
print('PR 292 tracker evidence updated')
