from pathlib import Path

path = Path('docs/VIDEO_EDIT_STUDIO_WYSIWYG_RENDERING_IMPLEMENTATION_PLAN_2026-08.md')
text = path.read_text(encoding='utf-8')

def replace_once(old: str, new: str) -> None:
    global text
    count = text.count(old)
    if count != 1:
        raise SystemExit(f'expected one match, found {count}: {old[:160]!r}')
    text = text.replace(old, new, 1)

replace_once(
"""- Because this lossless alpha path differs only by one RGB code value after browser-vs-FFmpeg source-over rounding, #294 freezes a **fixture-specific ±1 RGB gate with 100% pixel pass**. It does not weaken #289's zero-tolerance opaque PNG gate, #293's H.264 ±3 gate, or repository-global ±2/99.9% diagnostics.\n""",
"""- Because this lossless alpha path differs only by one RGB code value after browser-vs-FFmpeg source-over rounding, #294 freezes a **fixture-specific ±1 RGB gate with 100% pixel pass**. It does not weaken #289's zero-tolerance opaque PNG gate, #293's H.264 ±3 gate, or repository-global ±2/99.9% diagnostics.\n- Exact hard-gate head `db8cab44108b668eac5d870f68b939052eaad8cc` passed Video Pixelate Alpha Parity Evidence #6. Artifact `9727353580` is 10,861,146 bytes with SHA-256 `cbf77e96ba204a206ec61baea061c9ce549439d63ffa8621b82e970bf0d88824`; retained timeline SHA-256 is `34df731b6f19146546aae9187ec6894677ca7ffe1daa91d092ae6782a1e2df02`. Every 123,721-pixel region on frames `0/15/30/59` reports `max_channel_delta=1`, `alpha_gate_pass=true`, and the browser surface explicitly records `surface_background=#19324A`.\n- The same exact head also passed Video Pixelate Parity Evidence #59 (opaque-PNG byte-exact control plus H.264 decoded-frame identity/±3 control), Security Scan #1735, Quality Gate #1730 including frontend lint/unit/build, backend tests/vet/race detector, Playwright smoke, and the full 103-frame renderer parity baseline, plus all applicable Linux/macOS/browser/container assurance workflows. No PR comments, reviews, or unresolved review threads are present.\n"""
)

replace_once(
"""1. **Finish #294's exact-head gate.** Enforce the retained alpha PNG contract at `max_channel_delta <= 1` and 100% pixels within that envelope, while also retaining the resolved `#19324A` Canvas background value. Re-run the independent opaque-PNG zero-tolerance and H.264 frame-identity/±3 controls on the same exact head before merge.\n2. **Next slice after #294: transparent decoded-video readiness/alpha proof.** Keep transparent decoded video fail-closed until a reliable presentation/readiness signal can distinguish legitimate transparent decoded pixels from Chromium's post-seek not-yet-rasterizable state. Do not remove the H.264 source-only guard merely to broaden alpha support.\n3. After #294 is retained and green, broaden pixelate/weighted-Canvas raster eligibility only for painter/source classes whose source-over ordering is explicit and independently evidenced.\n4. Add resource-font fixture coverage and retain parity evidence on a second supported OS/FFmpeg environment before calling cross-machine Phase 0 visual identity closed.\n5. Continue Phase 3 with normal-playback canonicalization, explicit diagnostics/rollback, then shared AudioGraph consumption.\n""",
"""1. **Merge #294 after the tracker-bearing exact-head wave repeats the already-green implementation evidence.** The implementation/evidence head proves renderer-ordered project-background/source-over image-alpha composition at `surface_background=#19324A`, 100% of sampled region pixels within ±1 RGB, unchanged opaque-PNG byte exactness, and unchanged H.264 frame-identity/±3 behavior.\n2. **Next slice: transparent decoded-video presentation readiness.** Move rasterizability proof to the existing mounted `<video>` owner in `VideoPreviewCanvasLegacy`: clear a presentation token on each deterministic seek, fulfill it only from a post-seek `requestVideoFrameCallback` on that same element, and key it to the canonical requested source-time target/request serial rather than assuming project FPS equals source FPS.\n3. Let `PreviewPixelateCanvas` require that matching presentation token before painting decoded video; once readiness is independent of pixel alpha, alpha becomes content semantics and transparent video can be source-over composited like images. Keep the mounted `<video>` as the sole decoder and source-time authority.\n4. Add a deterministic transparent-video fixture only after verifying a Chromium+FFmpeg alpha-capable codec/container in the hosted toolchain; retain presentation-token identity plus browser↔renderer region evidence and fail closed when the codec/path is not deterministic.\n5. Broaden pixelate/weighted-Canvas raster eligibility only for painter/source classes whose source-over ordering is explicit and independently evidenced. Add resource-font fixture coverage and second-supported-OS/FFmpeg retained evidence before calling cross-machine Phase 0 visual identity closed.\n6. Continue Phase 3 with normal-playback canonicalization, explicit diagnostics/rollback, then shared AudioGraph consumption.\n"""
)

path.write_text(text, encoding='utf-8')
print('final PR 294 tracker evidence updated')
