package agent

import (
	"encoding/json"
	"time"

	"github.com/ajbergh/omnillm-studio/internal/models"
)

// --------------- Run status constants ---------------

const (
	RunStatusPlanning         = "planning"
	RunStatusRunning          = "running"
	RunStatusAwaitingApproval = "awaiting_approval"
	RunStatusPaused           = "paused"
	RunStatusCompleted        = "completed"
	RunStatusFailed           = "failed"
	RunStatusCancelled        = "cancelled"
)

// IsTerminalRunStatus returns true for statuses that indicate a run is finished.
func IsTerminalRunStatus(s string) bool {
	return s == RunStatusCompleted || s == RunStatusFailed || s == RunStatusCancelled
}

// --------------- Step status constants ---------------

const (
	StepStatusPending          = "pending"
	StepStatusRunning          = "running"
	StepStatusAwaitingApproval = "awaiting_approval"
	StepStatusCompleted        = "completed"
	StepStatusFailed           = "failed"
	StepStatusSkipped          = "skipped"
)

// --------------- Step type constants ---------------

const (
	StepTypeThink    = "think"
	StepTypeToolCall = "tool_call"
	StepTypeApproval = "approval"
	StepTypeMessage  = "message"
)

// ValidStepTypes is the set of accepted step types.
var ValidStepTypes = map[string]bool{
	StepTypeThink:    true,
	StepTypeToolCall: true,
	StepTypeApproval: true,
	StepTypeMessage:  true,
}

// --------------- Runner configuration ---------------

const (
	DefaultMaxSteps    = 20
	DefaultMaxDuration = 10 * time.Minute
)

// RunnerConfig holds configurable limits for agent execution.
type RunnerConfig struct {
	MaxSteps    int
	MaxDuration time.Duration
}

// DefaultRunnerConfig returns sensible defaults.
func DefaultRunnerConfig() RunnerConfig {
	return RunnerConfig{
		MaxSteps:    DefaultMaxSteps,
		MaxDuration: DefaultMaxDuration,
	}
}

// --------------- Data types ---------------

// PlanStep describes a single planned step generated by the planner.
type PlanStep struct {
	Type        string          `json:"type"` // think, tool_call, approval, message
	Description string          `json:"description"`
	ToolName    string          `json:"tool_name,omitempty"`  // for type=tool_call
	InputJSON   json.RawMessage `json:"input_json,omitempty"` // optional pre-filled args
}

// RunWithSteps bundles an agent run with its steps for API responses.
type RunWithSteps struct {
	models.AgentRun
	Steps []models.AgentStep `json:"steps"`
}

// StartRunRequest is the API request body for starting an agent run.
type StartRunRequest struct {
	Goal     string `json:"goal"`
	Provider string `json:"provider,omitempty"`
	Model    string `json:"model,omitempty"`
}

// ApproveRequest is the API request body for approving/rejecting a step.
type ApproveRequest struct {
	Approved bool   `json:"approved"`
	Feedback string `json:"feedback,omitempty"` // optional user feedback
}

// ParsePlan parses a JSON plan string into a slice of PlanSteps.
func ParsePlan(planJSON string) ([]PlanStep, error) {
	var steps []PlanStep
	if err := json.Unmarshal([]byte(planJSON), &steps); err != nil {
		return nil, err
	}
	return steps, nil
}

// EncodePlan serializes a slice of PlanSteps to JSON string.
func EncodePlan(steps []PlanStep) (string, error) {
	data, err := json.Marshal(steps)
	if err != nil {
		return "", err
	}
	return string(data), nil
}
