// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {main} from '../models';

export function GetAPIBase():Promise<string>;

export function ImportNativeCapture(arg1:string,arg2:string):Promise<Record<string, any>>;

export function NativeCaptureCapabilities():Promise<main.NativeCaptureCapabilitiesResponse>;

export function SelectSandboxWorkspace():Promise<string>;

export function StartNativeCapture(arg1:main.NativeCaptureRequest):Promise<Record<string, any>>;

export function StopNativeCapture(arg1:string):Promise<Record<string, any>>;
