package video

const (
	ParityPixelateOpaqueFixtureName       = "parity-pixelate-opaque-v1"
	ParityPixelateDecodedVideoFixtureName = "parity-pixelate-decoded-video-v1"
	ParityPixelateAlphaFixtureName        = "parity-pixelate-alpha-png-v1"
	ParityPixelateAlphaVideoFixtureName   = "parity-pixelate-alpha-video-v1"

	parityPixelateOpaqueCanvasWidth   = 512
	parityPixelateOpaqueCanvasHeight  = 512
	parityPixelateDecodedCanvasWidth  = 640
	parityPixelateDecodedCanvasHeight = 360
	parityPixelateFPS                 = 30
	parityPixelateDurationMS          = int64(2000)
	parityPixelateRegionWidth         = 403
	parityPixelateRegionHeight        = 307
	parityPixelateRegionX             = 17
	parityPixelateRegionY             = -8
	parityPixelateBlockSize           = 20
)

// ParityFixtureRegionFrame binds exact structural-region policy to canonical
// output frame identity. It is shared by focused fixture emitters and the
// parity-report manifest without relying on mutable screenshot filenames.
type ParityFixtureRegionFrame struct {
	FrameIndex int64          `json:"frame_index"`
	Regions    []ParityRegion `json:"regions"`
}

// ParityPixelateOpaqueFixture isolates the first preview-pixelate-raster-v1
// consumer path from the larger torture fixture. A 1:1 opaque PNG backdrop
// avoids codec/color-conversion noise while the non-divisible 403x307 region
// exercises the same floor downsample grid used by the legacy FFmpeg renderer.
func ParityPixelateOpaqueFixture() (TimelineDocument, []ParityFixtureAsset) {
	return parityPixelateFixture(
		ParityPixelateOpaqueFixtureName,
		parityPixelateOpaqueCanvasWidth,
		parityPixelateOpaqueCanvasHeight,
		"#000000",
		"asset-square",
		ParityFixtureAsset{ID: "asset-square", Kind: "image", Width: 512, Height: 512, DurationMS: parityPixelateDurationMS, Description: "opaque 512x512 deterministic PNG"},
		"Opaque pixelate source",
	)
}

// ParityPixelateDecodedVideoFixture keeps the same static pixelate semantics but
// replaces the lossless PNG control with the deterministic H.264/yuv420p source
// generated by video-parity-fixture. Matching the canvas to the source's
// 640x360 dimensions avoids an unrelated media-resize variable so retained
// differences isolate browser/FFmpeg decode and RGB color-conversion behavior.
func ParityPixelateDecodedVideoFixture() (TimelineDocument, []ParityFixtureAsset) {
	return parityPixelateFixture(
		ParityPixelateDecodedVideoFixtureName,
		parityPixelateDecodedCanvasWidth,
		parityPixelateDecodedCanvasHeight,
		"#000000",
		"asset-landscape",
		ParityFixtureAsset{ID: "asset-landscape", Kind: "video", Width: 640, Height: 360, DurationMS: 24000, Description: "deterministic H.264 yuv420p testsrc2 landscape video with stereo tone"},
		"Decoded H.264 pixelate source",
	)
}

// ParityPixelateAlphaFixture exercises the exact source-over order used by the
// renderer: opaque project background, straight-alpha PNG media, then pixelate.
// The generated PNG deliberately includes hidden RGB under alpha=0 plus several
// partial-alpha bands so a premultiplication or compositing-order mistake is
// visible in the retained pixelate region.
func ParityPixelateAlphaFixture() (TimelineDocument, []ParityFixtureAsset) {
	return parityPixelateFixture(
		ParityPixelateAlphaFixtureName,
		parityPixelateOpaqueCanvasWidth,
		parityPixelateOpaqueCanvasHeight,
		"#19324A",
		"asset-alpha",
		ParityFixtureAsset{ID: "asset-alpha", Kind: "image", Width: 512, Height: 512, DurationMS: parityPixelateDurationMS, Description: "deterministic NRGBA PNG with hidden RGB and 0/64/128/192/255 alpha"},
		"Partial-alpha PNG pixelate source",
	)
}

// ParityPixelateAlphaVideoFixture moves two partial-alpha regions over the same
// non-black project background used by the PNG alpha control. The source is a
// two-second VP9 WebM carrying alpha_mode=1. Frame content changes continuously
// so stale presentation identity and alpha loss cannot accidentally pass on a
// static raster.
func ParityPixelateAlphaVideoFixture() (TimelineDocument, []ParityFixtureAsset) {
	return parityPixelateFixture(
		ParityPixelateAlphaVideoFixtureName,
		parityPixelateOpaqueCanvasWidth,
		parityPixelateOpaqueCanvasHeight,
		"#19324A",
		"asset-alpha-video",
		ParityFixtureAsset{ID: "asset-alpha-video", Kind: "video", Width: 512, Height: 512, DurationMS: parityPixelateDurationMS, Description: "deterministic changing VP9 WebM with alpha_mode=1 and partial-alpha moving regions"},
		"Partial-alpha VP9 pixelate source",
	)
}

func parityPixelateFixture(name string, canvasWidth, canvasHeight int, background, assetID string, sourceAsset ParityFixtureAsset, sourceTrackName string) (TimelineDocument, []ParityFixtureAsset) {
	doc := NewEmptyTimeline(canvasWidth, canvasHeight, parityPixelateFPS)
	doc.DurationMS = parityPixelateDurationMS
	doc.Canvas.Background = background
	doc.Metadata = map[string]any{"fixture": name}

	mediaZ := 1
	pixelateZ := 20
	doc.Tracks = []TimelineTrack{
		{
			ID:      "track-pixelate-source",
			Type:    TrackTypeLayer,
			Name:    sourceTrackName,
			Visible: true,
			Clips: []TimelineClip{{
				ID:           "clip-pixelate-source",
				AssetID:      assetID,
				StartMS:      0,
				DurationMS:   parityPixelateDurationMS,
				TrimOutMS:    parityPixelateDurationMS,
				PlaybackRate: 1,
				ZIndex:       &mediaZ,
				Transform: map[string]any{
					"x": 0.0, "y": 0.0, "z": 0.0,
					"scale": 1.0, "rotation": 0.0, "opacity": 1.0,
				},
				Effects:   []TimelineEffect{},
				Keyframes: []TimelineKeyframe{},
			}},
		},
		{
			ID:      "track-pixelate-region",
			Type:    TrackTypeShape,
			Name:    "Exact opaque pixelate region",
			Visible: true,
			Clips: []TimelineClip{{
				ID:         "clip-pixelate-region",
				StartMS:    0,
				DurationMS: parityPixelateDurationMS,
				TrimOutMS:  parityPixelateDurationMS,
				ZIndex:     &pixelateZ,
				Transform: map[string]any{
					"x": float64(parityPixelateRegionX),
					"y": float64(parityPixelateRegionY),
					"z": 0.0, "scale": 1.0, "rotation": 0.0, "opacity": 1.0,
				},
				Shape: &TimelineShape{
					Kind:       ShapeKindPixelate,
					Width:      parityPixelateRegionWidth,
					Height:     parityPixelateRegionHeight,
					BlurRadius: parityPixelateBlockSize,
				},
				Effects:   []TimelineEffect{},
				Keyframes: []TimelineKeyframe{},
			}},
		},
		{
			ID:      "track-pixelate-audio",
			Type:    TrackTypeAudio,
			Name:    "Capture harness audio",
			Visible: true,
			Clips: []TimelineClip{{
				ID:           "clip-pixelate-audio",
				AssetID:      "asset-audio",
				StartMS:      0,
				DurationMS:   parityPixelateDurationMS,
				TrimOutMS:    parityPixelateDurationMS,
				PlaybackRate: 1,
				Effects:      []TimelineEffect{},
				Keyframes:    []TimelineKeyframe{},
			}},
		},
	}

	assets := []ParityFixtureAsset{
		sourceAsset,
		{ID: "asset-audio", Kind: "audio", DurationMS: parityPixelateDurationMS, Description: "deterministic mono swept tone and impulses"},
	}
	return doc, assets
}

// ParityPixelateOpaqueFrameSamples keeps the lossless control fixture small and
// deterministic while sampling the start, two interior frames, and final frame.
func ParityPixelateOpaqueFrameSamples() []ParityFrameSample {
	return parityPixelateFrameSamples("pixelate")
}

// ParityPixelateDecodedVideoFrameSamples binds the same canonical output-frame
// identities while making the changing codec-decoded source explicit in names.
func ParityPixelateDecodedVideoFrameSamples() []ParityFrameSample {
	return parityPixelateFrameSamples("pixelate-video")
}

// ParityPixelateAlphaFrameSamples repeats the static alpha composition at the
// same canonical frame identities used by the other focused pixelate controls.
func ParityPixelateAlphaFrameSamples() []ParityFrameSample {
	return parityPixelateFrameSamples("pixelate-alpha")
}

// ParityPixelateAlphaVideoFrameSamples uses the same canonical output-frame
// identities while requiring the changing transparent decoder to present each
// requested source frame.
func ParityPixelateAlphaVideoFrameSamples() []ParityFrameSample {
	return parityPixelateFrameSamples("pixelate-alpha-video")
}

func parityPixelateFrameSamples(prefix string) []ParityFrameSample {
	return []ParityFrameSample{
		{Name: prefix + "-start", FrameIndex: 0, TimeMS: 0, Reason: "pixelate region start"},
		{Name: prefix + "-quarter", FrameIndex: 15, TimeMS: 500, Reason: "opaque pixelate interior"},
		{Name: prefix + "-half", FrameIndex: 30, TimeMS: 1000, Reason: "opaque pixelate interior"},
		{Name: prefix + "-final", FrameIndex: 59, TimeMS: 1967, Reason: "final active pixelate frame"},
	}
}

// ParityPixelateOpaqueRegionBounds mirrors the legacy renderer's integer
// center-relative region placement for the 512x512 lossless control fixture.
func ParityPixelateOpaqueRegionBounds() ParityBounds {
	return parityPixelateRegionBounds(parityPixelateOpaqueCanvasWidth, parityPixelateOpaqueCanvasHeight)
}

// ParityPixelateDecodedVideoRegionBounds mirrors the same placement semantics on
// the 640x360 decoded-video canvas without introducing source rescaling.
func ParityPixelateDecodedVideoRegionBounds() ParityBounds {
	return parityPixelateRegionBounds(parityPixelateDecodedCanvasWidth, parityPixelateDecodedCanvasHeight)
}

// ParityPixelateAlphaRegionBounds shares the 512x512 structural rectangle with
// the lossless opaque control while changing only source alpha/background.
func ParityPixelateAlphaRegionBounds() ParityBounds {
	return parityPixelateRegionBounds(parityPixelateOpaqueCanvasWidth, parityPixelateOpaqueCanvasHeight)
}

// ParityPixelateAlphaVideoRegionBounds shares the transparent-PNG rectangle so
// the retained video evidence changes only source codec/presentation semantics.
func ParityPixelateAlphaVideoRegionBounds() ParityBounds {
	return parityPixelateRegionBounds(parityPixelateOpaqueCanvasWidth, parityPixelateOpaqueCanvasHeight)
}

func parityPixelateRegionBounds(canvasWidth, canvasHeight int) ParityBounds {
	minX := (canvasWidth-parityPixelateRegionWidth)/2 + parityPixelateRegionX
	minY := (canvasHeight-parityPixelateRegionHeight)/2 + parityPixelateRegionY
	return ParityBounds{
		MinX: minX,
		MinY: minY,
		MaxX: minX + parityPixelateRegionWidth,
		MaxY: minY + parityPixelateRegionHeight,
	}
}

// ParityPixelateOpaqueRegionFrames requires an exact structural comparison of
// every sampled pixelate output rectangle for the lossless PNG control.
func ParityPixelateOpaqueRegionFrames(samples []ParityFrameSample) []ParityFixtureRegionFrame {
	return parityPixelateRegionFrames(samples, ParityPixelateOpaqueRegionBounds())
}

// ParityPixelateDecodedVideoRegionFrames binds the decoded-video measurement
// region to exact frame identity. The tolerant codec report consumes these
// bounds without weakening the lossless structural-exactness policy.
func ParityPixelateDecodedVideoRegionFrames(samples []ParityFrameSample) []ParityFixtureRegionFrame {
	return parityPixelateRegionFrames(samples, ParityPixelateDecodedVideoRegionBounds())
}

// ParityPixelateAlphaRegionFrames binds source-over alpha composition evidence
// to the same exact 403x307 region policy as the lossless PNG control.
func ParityPixelateAlphaRegionFrames(samples []ParityFrameSample) []ParityFixtureRegionFrame {
	return parityPixelateRegionFrames(samples, ParityPixelateAlphaRegionBounds())
}

// ParityPixelateAlphaVideoRegionFrames binds changing transparent-video output
// to exact canonical frame identities and the established pixelate rectangle.
func ParityPixelateAlphaVideoRegionFrames(samples []ParityFrameSample) []ParityFixtureRegionFrame {
	return parityPixelateRegionFrames(samples, ParityPixelateAlphaVideoRegionBounds())
}

func parityPixelateRegionFrames(samples []ParityFrameSample, bounds ParityBounds) []ParityFixtureRegionFrame {
	frames := make([]ParityFixtureRegionFrame, 0, len(samples))
	for _, sample := range samples {
		frames = append(frames, ParityFixtureRegionFrame{
			FrameIndex: sample.FrameIndex,
			Regions: []ParityRegion{{
				Name:   "pixelate-output",
				Bounds: bounds,
			}},
		})
	}
	return frames
}
